### ISSUE TITLE
Criar método de indicar artigo

### ISSUE THREAD

**Issue by cantuariavc** [ads-unbind/unbind#106]

**Comment by aquiles23** [comment]
pelo que conversei com @saraivinha97  nessa issue é para que pegue o somatório das perguntas(não implementado direito ainda ao que parece) e capture a CATEGORIA em que o usuario ganhou mais pontos. depois o sistema indica os ARTIGOS daquela CATEGORIA para o usuario.
já criei a view em que exibe os artigos que foram indicados pelo usuário.
Falta também corrigir a maneira como está sendo registrado o usuario pois só é registrado o User(padrão do django) e não o Usuario que vai guardar os artigos.
