### ISSUE TITLE
Criar rotas de artigos gerais

### ISSUE THREAD

**Issue by cantuariavc** [ads-unbind/unbind#110]

**Comment by IgorVeludo2** [comment]
O que seria Artigos Gerais? Qual a diferença de Artigo Geral para Artigo? E Artigo Personalizado? Quais rotas devem ser geradas? CRUD?

**Comment by roginaldosemog** [comment]
Dê uma olhada nos documentos do projeto, e na resposta da issue #111, para entender melhor.

**Comment by geovanne97** [comment]
então, na tela index antes do usuário fazer o login, no navbar vai ter uma rota que liga pra todas as categorias de tds os artigos, qnd o usuário clica nessa rota ele encaminha pra uma page que print tds as categorias, o usuário ao clicar em uma das categorias printadas linkará pra tds os artigos que pertencem a essa categoria, essa nova tela aparecerá tds os artigos, com o título e a descrição
