### ISSUE TITLE
Corrigir o fluxo de artigos gerais, de acordo com o diagrama de casos de uso

### ISSUE THREAD

**Issue by cantuariavc** [ads-unbind/unbind#111]

**Comment by IgorVeludo2** [comment]
Qual o problema que devo corrigir? Não entendi bem isso..

**Comment by roginaldosemog** [comment]
As rotas para acessar os artigos. 
Ex: Home -> Lista de Artigos -> Artigo

Acesse o diagrama de caso de uso para melhor compreensão;
