### ISSUE TITLE
GH Page da wiki não funciona

### ISSUE THREAD

**Issue by cantuariavc** [ads-unbind/unbind#7]
**Descrição do bug**
Deploy do gh pages da wiki não está acontecendo de forma correta.

**Para reproduzir**
Passos para reproduzir o bug:
1. Vá para acesse o link [https://ads-2019-1.github.io/ads-2019-1/](https://ads-2019-1.github.io/ads-2019-1/)
2. Veja o erro

**Comportamento esperado**
Quando clicado no link, a página deveria estar funcionando.

**Screenshots**
![Captura de Tela 2019-03-24 às 18 32 18](https://user-images.githubusercontent.com/21143590/54886148-70a37480-4e63-11e9-8b99-4846857ef31e.png)

**Informações Adicionais**
Comandos do mkdocs:
```
mkdocs build
mkdocs serve
```

**Comment by byronkamal** [comment]
@cantuariavc é melhor criar uma branch chamada gh-pages.
Lá dentro deve ser colocado somente o que foi gerado dentro da pasta docs, depois que foi rodado o comando `mkdocs build`. No meu projeto de MDS funcionou dessa forma.
Para ver as estruturas das pastas, pode olhar em: [https://github.com/fga-eps-mds/2018.1-IncluCare_API/tree/gh-pages](url)

**Comment by cantuariavc** [comment]
Você pode fazer essa configuração inicial, @byronkamal ?

**Comment by byronkamal** [comment]
@cantuariavc Posso.
E vou ver uma forma de automatizar o deploy da pagina.

**Comment by byronkamal** [comment]
Configuração inicial feita.

**Comment by byronkamal** [comment]
https://ads-2019-1.github.io/ads-2019-1/
