### ISSUE TITLE
criar model-artigo

### ISSUE THREAD

**Issue by geovanne97** [ads-unbind/unbind#76]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**
Descreva de forma clara e concisa qual é o problema. Ex. Eu fico frustrado quando [...]

**Descreva a solução que você gostaria**
Descreva de forma clara e concisa do que você quer que aconteça.

**Descreva uma alternativa considerada**
Descreva de forma clara e concisa qualquer solução alternativa ou alguma funcionalidade considerada.

**Informações adicionais**
Comente outra informação relevante sobre o sua funcionalidade requisitada aqui

**Comment by cantuariavc** [comment]
https://github.com/ads-unbind/unbind/tree/master/src/artigo
